In [5]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [6]:
# 1. 과거의 데이터를 준비한다.
iris = pd.read_csv('./csv/iris.csv')
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [7]:
# 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [8]:
encoding.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [9]:
# 독립변수, 종속변수 분리
independent = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
subordination = encoding[['품종_setosa', '품종_versicolor','품종_virginica']]
print(independent.shape, subordination.shape)

(150, 4) (150, 3)


In [10]:
# 2. 모델의 구조를 만든다.
x = tf.keras.layers.Input(shape=[4])
h = tf.keras.layers.Dense(8, activation='swish')(x)
h = tf.keras.layers.Dense(8, activation='swish')(h)
h = tf.keras.layers.Dense(8, activation='swish')(h)
y = tf.keras.layers.Dense(3, activation='softmax')(h)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [13]:
model.fit(independent, subordination, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 5ms/step - loss: 0.1998 - accuracy: 0.9467
Epoch 2/100
5/5 [==============================] - 0s 6ms/step - loss: 0.1947 - accuracy: 0.9467
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 0.1933 - accuracy: 0.9533
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 0.1931 - accuracy: 0.9467
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 0.1881 - accuracy: 0.9467
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 0.1905 - accuracy: 0.9600
Epoch 7/100
5/5 [==============================] - 0s 6ms/step - loss: 0.1813 - accuracy: 0.9533
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 0.1793 - accuracy: 0.9467
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 0.1772 - accuracy: 0.9533
Epoch 10/100
5/5 [==============================] - 0s 6ms/step - loss: 0.1841 - accuracy: 0.9533
Epoch 11/100
5/5 [===========

In [15]:
print(model.predict(independent[-5:]).round(3))
print(subordination[-5:])

1/1 [==============================] - 0s 41ms/step
[[0.    0.035 0.965]
 [0.    0.114 0.886]
 [0.    0.128 0.872]
 [0.    0.027 0.973]
 [0.    0.267 0.733]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [17]:
model.get_weights()

[array([[-0.46144745,  0.28950706,  0.17878267,  0.32617053,  0.8160762 ,
         -0.18609919, -0.07867959, -0.08457613],
        [ 0.17612977, -0.8589233 ,  0.9027135 , -0.3530393 , -0.24129102,
          0.14576098,  0.03821345,  0.25304756],
        [ 0.51032394,  0.6880157 , -1.0245526 ,  0.31266966,  0.7553634 ,
         -0.47256753, -0.27327356, -0.2093588 ],
        [ 0.536494  ,  0.26537016, -0.8480515 ,  0.66082275, -0.10838059,
          0.2756867 , -0.59759927, -0.87191284]], dtype=float32),
 array([ 0.09227166, -0.21190554,  0.33457407, -0.31798097,  0.17977566,
         0.28158534,  0.40020725, -0.04509494], dtype=float32),
 array([[ 1.19967163e-02, -4.60815849e-04, -1.73528135e-01,
         -8.03729892e-01,  3.24174225e-01, -8.84860814e-01,
         -8.72333944e-01, -3.18227947e-01],
        [ 8.00937295e-01, -9.45368260e-02, -2.38790393e-01,
         -7.28556693e-01, -8.03147435e-01, -1.06495604e-01,
          4.74078089e-01,  4.56850380e-01],
        [ 3.15271318e-01, 