In [31]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [32]:
# 1. 과거의 데이터를 준비한다.
iris = pd.read_csv('./csv/iris.csv')
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [33]:
# 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [34]:
encoding.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [35]:
# 독립변수, 종속변수 분리
independent = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
subordination = encoding[['품종_setosa', '품종_versicolor','품종_virginica']]
print(independent.shape, subordination.shape)

(150, 4) (150, 3)


In [36]:
# 2. 모델의 구조를 만든다.
x = tf.keras.layers.Input(shape=[4])

h = tf.keras.layers.Dense(8)(x)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(8)(h)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(8)(h)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

y = tf.keras.layers.Dense(3, activation='softmax')(h)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [37]:
model.fit(independent, subordination, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 4s 10ms/step - loss: 1.2325 - accuracy: 0.3267
Epoch 2/1000
5/5 [==============================] - 0s 5ms/step - loss: 1.1258 - accuracy: 0.3933
Epoch 3/1000
5/5 [==============================] - 0s 6ms/step - loss: 1.0613 - accuracy: 0.4200
Epoch 4/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.9907 - accuracy: 0.5000
Epoch 5/1000
5/5 [==============================] - 0s 6ms/step - loss: 0.9342 - accuracy: 0.5200
Epoch 6/1000
5/5 [==============================] - 0s 10ms/step - loss: 0.8684 - accuracy: 0.6133
Epoch 7/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.8335 - accuracy: 0.6333
Epoch 8/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.8161 - accuracy: 0.6867
Epoch 9/1000
5/5 [==============================] - 0s 14ms/step - loss: 0.7648 - accuracy: 0.8200
Epoch 10/1000
5/5 [==============================] - 0s 8ms/step - loss: 0.7217 - accuracy: 0.8667
Epoch 11/1000
5/

In [38]:
print(model.predict(independent[-5:]).round(3))
print(subordination[-5:])

1/1 [==============================] - 1s 548ms/step
[[0.    0.    1.   ]
 [0.    0.018 0.982]
 [0.    0.014 0.986]
 [0.    0.028 0.972]
 [0.    0.331 0.669]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [39]:
model.get_weights()

[array([[-0.13767223,  0.27116802,  0.18015459, -0.53851855, -0.23473515,
          0.10781062, -0.11899421,  0.0247489 ],
        [-0.5385795 , -0.3175384 , -0.36210144, -0.06384651,  0.0831559 ,
          0.13322434, -0.2093335 ,  0.5717692 ],
        [ 0.05093376,  0.04921595, -0.89401615, -0.31657436,  0.10847915,
          0.19654654,  0.60168064, -0.5892805 ],
        [ 0.7177811 ,  0.49949864, -0.0433589 , -0.49012953,  0.3931272 ,
         -0.76191854, -0.0525056 , -0.12794343]], dtype=float32),
 array([ 0.00623164,  0.00305143, -0.00046416,  0.00099444, -0.01774721,
         0.00438889, -0.00131225, -0.0048978 ], dtype=float32),
 array([0.80983967, 0.9225657 , 1.0382631 , 1.0770565 , 1.0650464 ,
        0.9758542 , 0.85800433, 1.0346692 ], dtype=float32),
 array([-0.09397473, -0.12163595,  0.09979234,  0.0742492 ,  0.14344876,
         0.17498682, -0.05828729, -0.04316331], dtype=float32),
 array([-1.3727582 ,  1.4713608 , -3.4747245 , -5.133496  , -0.24789362,
         0.8828