In [26]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [27]:
# 1. 과거의 데이터를 준비한다.
iris = pd.read_csv('./csv/iris.csv')
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [28]:
# 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [29]:
encoding.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [30]:
# 독립변수, 종속변수 분리
independent = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
subordination = encoding[['품종_setosa', '품종_versicolor','품종_virginica']]
print(independent.shape, subordination.shape)

(150, 4) (150, 3)


In [31]:
# 2. 모델의 구조를 만든다.
x = tf.keras.layers.Input(shape=[4])
y = tf.keras.layers.Dense(3, activation='softmax')(x)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [32]:
model.fit(independent, subordination, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 4ms/step - loss: 6.0798 - accuracy: 0.3333
Epoch 2/1000
5/5 [==============================] - 0s 4ms/step - loss: 5.9056 - accuracy: 0.3333
Epoch 3/1000
5/5 [==============================] - 0s 3ms/step - loss: 5.7792 - accuracy: 0.3333
Epoch 4/1000
5/5 [==============================] - 0s 9ms/step - loss: 5.6657 - accuracy: 0.3333
Epoch 5/1000
5/5 [==============================] - 0s 3ms/step - loss: 5.5601 - accuracy: 0.3333
Epoch 6/1000
5/5 [==============================] - 0s 3ms/step - loss: 5.4602 - accuracy: 0.3333
Epoch 7/1000
5/5 [==============================] - 0s 3ms/step - loss: 5.3653 - accuracy: 0.3333
Epoch 8/1000
5/5 [==============================] - 0s 3ms/step - loss: 5.2708 - accuracy: 0.3333
Epoch 9/1000
5/5 [==============================] - 0s 3ms/step - loss: 5.1790 - accuracy: 0.3333
Epoch 10/1000
5/5 [==============================] - 0s 3ms/step - loss: 5.0885 - accuracy: 0.3333
Epoch 11/1000
5/5 [

In [33]:
print(model.predict(independent[-5:]).round(3))

1/1 [==============================] - 0s 84ms/step
[[0.    0.102 0.898]
 [0.    0.188 0.812]
 [0.    0.212 0.788]
 [0.    0.063 0.937]
 [0.    0.226 0.774]]


In [34]:
subordination[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [35]:
model.get_weights()

[array([[ 1.1635152 ,  0.58816785, -0.76596874],
        [ 3.2242668 ,  0.800126  , -0.28751191],
        [-3.270786  , -0.07722449,  1.3740343 ],
        [-4.6166644 , -1.3878448 ,  2.3714528 ]], dtype=float32),
 array([ 1.4239956 ,  0.737966  , -0.94930196], dtype=float32)]